export const requiredOperationSummaryHeaders = [
  'Trip ID',
  'Corp Name',
  'Trip Date',
  'Trip type',
  'Trip Time',
  'Route No',
  'Route Name',
  'Vehicle No.',
  'Driver Name',
  'Driver Designation',
  'Attender Name',
  'Attender Designation',
  'Source Name',
  'Scheduled Start/End Time',
  'Actual Start Time',
  'Source Lateness',
  'Corp Entry/Exit',
  'Lateness',
  'Late By',
  'Late Due To',
  'FirstPointVisit',
  'ScheduleTime4FirstPoint',
  'ActualTime4FirstPoint',
  'Vehicle Capacity',
  'Expected Distance in KM',
  'Actual Distance in KM',
  '1st/Last Point visted order',
  'Dry Run Km',
  'Schedule Stoppages',
  'Skipped Stoppages',
  'Speed Violation',
  'Harsh Breaking',
  'Harsh Cornering',
  'Harsh Acceleration',
  'Destination',
  'ScheduledTime 4LastPoint',
  'ActualTime 4LastPoint',
  'LastPointLateness',
  'Scheduled Commuter',
  'Confirm Commuter',
  'Missed Commuter',
  'Own Transport Commuter',
  'Vendor Name',
  'Tracking Mode'
];

export const columnMap: Record<string, string> = {
  'Trip ID': 'trip_id',
  'Corp Name': 'corp_name',
  'Trip Date': 'trip_date',
  'Trip type': 'trip_type',
  'Trip Time': 'trip_time',
  'Route No': 'route_no',
  'Route Name': 'route_name',
  'Vehicle No.': 'vehicle_no',
  'Driver Name': 'driver_name',
  'Driver Designation': 'driver_designation',
  'Attender Name': 'attender_name',
  'Attender Designation': 'attender_designation',
  'Source Name': 'source_name',
  'Scheduled Start/End Time': 'scheduled_start_end_time',
  'Actual Start Time': 'actual_start_time',
  'Source Lateness': 'source_lateness',
  'Corp Entry/Exit': 'corp_entry_exit',
  'Lateness': 'lateness',
  'Late By': 'late_by',
  'Late Due To': 'late_due_to',
  'FirstPointVisit': 'first_point_visit',
  'ScheduleTime4FirstPoint': 'schedule_time_first_point',
  'ActualTime4FirstPoint': 'actual_time_first_point',
  'Vehicle Capacity': 'vehicle_capacity',
  'Expected Distance in KM': 'expected_distance_km',
  'Actual Distance in KM': 'actual_distance_km',
  '1st/Last Point visted order': 'first_last_point_visited_order',
  'Dry Run Km': 'dry_run_km',
  'Schedule Stoppages': 'schedule_stoppages',
  'Skipped Stoppages': 'skipped_stoppages',
  'Speed Violation': 'speed_violation',
  'Harsh Breaking': 'harsh_braking',
  'Harsh Cornering': 'harsh_cornering',
  'Harsh Acceleration': 'harsh_acceleration',
  'Destination': 'destination',
  'ScheduledTime 4LastPoint': 'scheduled_time_last_point',
  'ActualTime 4LastPoint': 'actual_time_last_point',
  'LastPointLateness': 'last_point_lateness',
  'Scheduled Commuter': 'scheduled_commuter',
  'Confirm Commuter': 'confirm_commuter',
  'Missed Commuter': 'missed_commuter',
  'Own Transport Commuter': 'own_transport_commuter',
  'Vendor Name': 'vendor_name',
  'Tracking Mode': 'tracking_mode'
};
