export const requiredSpareUtilizationHeaders = [
  'Corp Name',
  'requestID',
  'Date',
  'Time',
  'Trip Type',
  'Trip ID',
  'Trip Name',
  'Route',
  'Vehicle Number',
  'Scheduled Emp',
  'Scheduled Employee ID',
  'Actual Emp',
  'Reason',
  'Requested Amount',
  'Approved Amount',
  'Debit Amount',
  'PBC',
  'Debit from',
  'Requested By',
  'Requested On',
  'Actioned By',
  'Actioned On',
  'Status',
  'comment'
];

export const spareUtilizationColumnMap: Record<string, string> = {
  'Corp Name': 'corp_name',
  requestID: 'request_id',
  Date: 'request_date',
  Time: 'request_time',
  'Trip Type': 'trip_type',
  'Trip ID': 'trip_id',
  'Trip Name': 'trip_name',
  Route: 'route',
  'Vehicle Number': 'vehicle_number',
  'Scheduled Emp': 'scheduled_emp',
  'Scheduled Employee ID': 'scheduled_employee_id',
  'Actual Emp': 'actual_emp',
  Reason: 'reason',
  'Requested Amount': 'requested_amount',
  'Approved Amount': 'approved_amount',
  'Debit Amount': 'debit_amount',
  PBC: 'pbc',
  'Debit from': 'debit_from',
  'Requested By': 'requested_by',
  'Requested On': 'requested_on',
  'Actioned By': 'actioned_by',
  'Actioned On': 'actioned_on',
  Status: 'status',
  comment: 'comment'
};
